name: Deploy to DigitalOcean Droplet
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist


      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: temp


      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |

            # On your server
            # Move the build files to the desired location
            mv temp/dist /home/deployer/test/build

            # Clean up
            rm -rf temp

            echo 'Deployment to DigitalOcean finished'

