name: Deploy to DigitalOcean Droplet
'on':
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: aytarakdemir/comms-ear-training@main
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            rm -rf test
            mkdir test
            cd test
            git clone git@github.com:aytarakdemir/comms-ear-training.git
            echo 'Deployment to digital ocean finished'
            actions/checkout Default: ${{ github.repository }}